name: build and deploy node

on:
  workflow_call:
    secrets:
      hangfireFeedUrl:
        required: true  
      hangfireUsername:
        required: true
      hangfirePassword:
        required: true
      nexusAptRepoUsername:
        required: true
      nexusAptRepoPassword:
        required: true
      nexusAptRepoHost:
        required: true 
      nexusAptRepoPrereleaseHost:
        required: true  
      nexusDockerUsername:
        required: true  
      nexusDockerPassword:
        required: true 
      nugetGithubHost:
        required: true
      nugetGithubUsername:
        required: true
      nugetGithubPassword:
        required: true
      packageRepoHost: 
        required: true
      packageRepoPassword:
        required: true
      packageRepoUsername:
        required: true
      packageRepoPort:
        required: true
      dockerRepo:
        required: true 
jobs:
  build_and_publish_docker:
    uses: Hectors-Welt/SharedWorkflows/.github/workflows/node/node_latest_build_and_publish_docker_image.yml@main
    secrets:
      dockerRepo: ${{ secrets.DOCKER_REPO }}
      nexusDockerUsername: ${{ secrets.NEXUS_DOCKER_USERNAME }}
      nexusDockerPassword: ${{ secrets.NEXUS_DOCKER_PASSWORD }}
      packageRegistryToken: ${{ secrets.PACKAGE_REGISTRY_TOKEN }}
        
    
