name: Build and deploy

on:
  workflow_call:

jobs:
   build_and_publish_deb:
     if: ${{ always() && hashFiles('package.json') }}
     uses: Hectors-Welt/SharedWorkflows/.github/workflows/test.yml@main
        
