name: Build and deploy

on:
  workflow_call:
    secrets:
      hangfireFeedUrl:
        required: true  
      hangfireUsername:
        required: true
      hangfirePassword:
        required: true
      nexusAptRepoUsername:
        required: true
      nexusAptRepoPassword:
        required: true
      nexusAptRepoHost:
        required: true 
      nexusAptRepoPrereleaseHost:
        required: true  
      nexusDockerUsername: 
        required: true
      nexusDockerPassword:
        required: true
      nugetGithubHost:
        required: true
      nugetGithubUsername:
        required: true
      nugetGithubPassword:
        required: true
      packageRepoHost: 
        required: true
      packageRepoPassword:
        required: true
      packageRepoUsername:
        required: true
      packageRepoPort:
        required: true
      dockerRepo:
        required: true        


jobs:
  check:
     runs-on: ubuntu-latest
     steps:
      - name: Check if file was created
        run: |
          if [ -f package.json ]; then
              echo "runtime=node" >> $GITHUB_OUTPUT
              echo node
          else
              echo "runtime=dotnet" >> $GITHUB_OUTPUT
              echo dotnet
          fi     
  debug:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - env:
          OUTPUT1: ${{needs.check.outputs.runtime}}
        run: echo "$OUTPUT1"   
  dotnet:
      needs: check
      if: ${{ needs.check.outputs.runtime == 'dotnet' }} 
      uses: Hectors-Welt/SharedWorkflows/.github/workflows/build_and_deploy_dotnet.yml@main
      secrets:
        nexusAptRepoUsername: ${{ secrets.nexusAptRepoUsername }}
        nexusAptRepoPassword: ${{ secrets.nexusAptRepoPassword }}
        nexusAptRepoPrereleaseHost: ${{ secrets.nexusAptRepoPrereleaseHost }}
        nexusAptRepoHost: ${{ secrets.nexusAptRepoHost}}
        hangfireFeedUrl: ${{ secrets.hangfireFeedUrl }}
        hangfireUsername: ${{ secrets.hangfireUsername }}
        hangfirePassword: ${{ secrets.hangfirePassword }}
        nugetGithubHost: ${{ secrets.nugetGithubHost }}
        nugetGithubUsername: ${{ secrets.nugetGithubUsernam }}
        nugetGithubPassword: ${{ secrets.nugetGithubPassword }}
        packageRepoHost: ${{ secrets.packageRepoHost }}
        packageRepoPassword: ${{ secrets.packageRepoPassword }}
        packageRepoUsername: ${{ secrets.packageRepoUsername }}
        packageRepoPort: ${{ secrets.packageRepoPort }}
        dockerRepo: ${{ secrets.dockerRepo }}
        nexusDockerUsername: ${{ secrets.nexusDockerUsername }}
        nexusDockerPassword: ${{ secrets.nexusDockerPassword }}

  node:
      needs: check
      if: ${{ needs.check.outputs.runtime == 'node' }} 
      uses: Hectors-Welt/SharedWorkflows/.github/workflows/build_and_deploy_node.yml@main
      secrets:
        nexusAptRepoUsername: ${{ secrets.nexusAptRepoUsername }}
        nexusAptRepoPassword: ${{ secrets.nexusAptRepoPassword }}
        nexusAptRepoPrereleaseHost: ${{ secrets.nexusAptRepoPrereleaseHost }}
        nexusAptRepoHost: ${{ secrets.nexusAptRepoHost}}
        hangfireFeedUrl: ${{ secrets.hangfireFeedUrl }}
        hangfireUsername: ${{ secrets.hangfireUsername }}
        hangfirePassword: ${{ secrets.hangfirePassword }}
        nugetGithubHost: ${{ secrets.nugetGithubHost }}
        nugetGithubUsername: ${{ secrets.nugetGithubUsernam }}
        nugetGithubPassword: ${{ secrets.nugetGithubPassword }}
        packageRepoHost: ${{ secrets.packageRepoHost }}
        packageRepoPassword: ${{ secrets.packageRepoPassword }}
        packageRepoUsername: ${{ secrets.packageRepoUsername }}
        packageRepoPort: ${{ secrets.packageRepoPort }}
        dockerRepo: ${{ secrets.dockerRepo }}
        nexusDockerUsername: ${{ secrets.nexusDockerUsername }}
        nexusDockerPassword: ${{ secrets.nexusDockerPassword }}
        

