name: Build and deploy

on:
  workflow_call:

jobs:
  check:
     runs-on: ubuntu-latest
     steps:
      - name: Check if file was created
        run: |
          if [ -f package.json ]; then
              echo RUNTIME=$(echo node) >> $GITHUB_OUTPUT
          else
              echo RUNTIME=$(echo dotnet) >> $GITHUB_OUTPUT

          fi     
      
  build_and_deploy:
      if: ${{needs.check.outputs.RUNTIME}} == 'node'
      uses: Hectors-Welt/SharedWorkflows/.github/workflows/test.yml@main

