name: Build and deploy

on:
  workflow_call:

jobs:
  check:
     runs-on: ubuntu-latest
     steps:
      - name: Check if file was created
        run: |
          if [ -f package.json ]; then
              echo RUNTIME=$(echo node) >> $GITHUB_OUTPUT
          else
              echo RUNTIME=$(echo node) >> $GITHUB_OUTPUT
          fi     
      
  build_and_deploy:
      needs: check
      if: startsWith(github.ref, 'refs/tags/staging-')
      uses: Hectors-Welt/SharedWorkflows/.github/workflows/test.yml@main

