name: Create v6 publish zip

on:
  workflow_call:
    secrets:
      packageRepoHost: 
        required: true
      packageRepoPassword:
        required: true
      packageRepoUsername:
        required: true
      packageRepoPort:
        required: true
      hangfireFeedUrl:
        required: true  
      hangfireUsername:
        required: true
      hangfirePassword:
        required: true  
      nugetGithubHost:
        required: true
      nugetGithubUsername:
        required: true
      nugetGithubPassword:
        required: true
      dotnetVersion:
        required: true
 
env:
  SERVICE: ${{ github.event.repository.name }}
        
jobs:
   build_and_publish_zip:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ secrets.dotnetVersion }}.x
          
      - name: Prepare environment variables for release
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo BASE_VERSION=$(echo ${GITHUB_REF/refs\/tags\/v/}) >> $GITHUB_ENV
          echo VERSION=$(echo ${GITHUB_REF/refs\/tags\/v/}.$GITHUB_RUN_NUMBER) >> $GITHUB_ENV
          echo TAG_NAME=$(echo ${GITHUB_REF/refs\/tags\/}) >> $GITHUB_ENV
          echo NAME=$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}') >> $GITHUB_ENV
          
      - name: Prepare environment variables for staging
        if: startsWith(github.ref, 'refs/tags/staging-')
        run: |
          echo BASE_VERSION=$(echo ${GITHUB_REF/refs\/tags\/staging-/}) >> $GITHUB_ENV
          echo VERSION=$(echo ${GITHUB_REF/refs\/tags\/staging-/}.$GITHUB_RUN_NUMBER) >> $GITHUB_ENV
          echo TAG_NAME=$(echo ${GITHUB_REF/refs\/tags\/}) >> $GITHUB_ENV
          echo NAME=$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}') >> $GITHUB_ENV

      - name: Prepare environment variables for prerelease
        if: startsWith(github.ref, 'refs/tags/prerelease-')
        run: |
          echo BASE_VERSION=$(echo ${GITHUB_REF/refs\/tags\/prerelease-/}) >> $GITHUB_ENV
          echo VERSION=$(echo ${GITHUB_REF/refs\/tags\/prerelease-/}.$GITHUB_RUN_NUMBER) >> $GITHUB_ENV
          echo RUN_NUMBER=$(echo $GITHUB_RUN_NUMBER) >> $GITHUB_ENV
          echo TAG_NAME=$(echo ${GITHUB_REF/refs\/tags\/}) >> $GITHUB_ENV
          echo NAME=$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}') >> $GITHUB_ENV

      - name: If release, check if staging tag exists and get run number
        if: startsWith(github.ref, 'refs/tags/v')
        id: check_staging_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_VERSION=${{ env.BASE_VERSION }}
          STAGING_TAG_NAME="staging-$TAG_VERSION"
          REPO=${{ github.repository }}
          API_RESPONSE=$(curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/$REPO/git/ref/tags/$STAGING_TAG_NAME)
          echo $API_RESPONSE
          if [[ $API_RESPONSE == *"ref"* ]]; then
            COMMIT_SHA=$(echo $API_RESPONSE | jq -r '.object.sha')
            RUN_NUMBER=$(curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/$REPO/actions/runs | jq -r '[.workflow_runs[] | select(.head_branch == "'$STAGING_TAG_NAME'" and .conclusion == "success")] | max_by(.run_number) | .run_number')            
            echo "STAGING_TAG_EXISTS=true" >> $GITHUB_ENV
            echo "STAGING_RUN_NUMBER='$RUN_NUMBER'" >> $GITHUB_ENV
          else
            echo "STAGING_TAG_EXISTS=false" >> $GITHUB_ENV
          fi

    
      - name: If release, check if hotfix
        if: startsWith(github.ref, 'refs/tags/v')
        id: hotfix_check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
        
          REPO="${{ github.repository }}"
          GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          CURRENT_TAG="${GITHUB_REF#refs/tags/}"
  
          IFS='.' read -ra VERSION <<< "$CURRENT_TAG"
          MAJOR=${VERSION[0]#v}
          MINOR=${VERSION[1]}
          PATCH=${VERSION[2]}
  
          if [ "$PATCH" -gt 0 ]; then
            PATCH=$((PATCH-1))
            HOTFIX_TAG="v$MAJOR.$MINOR.$PATCH"
  
            TAGS=$(curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/$REPO/git/refs/tags)
  
            if echo $TAGS | jq -e --arg tag "refs/tags/$HOTFIX_TAG" '.[] | select(.ref == $tag)' > /dev/null; then
              echo "HOTFIX_STATUS=success" >> $GITHUB_ENV
            else
              echo "HOTFIX_STATUS=failure" >> $GITHUB_ENV
            fi
          else
            echo "HOTFIX_STATUS=failure" >> $GITHUB_ENV
          fi 
          
      - name: if no release, add feeds
        if: ${{!startsWith(github.ref, 'refs/tags/v') || ( startsWith(github.ref, 'refs/tags/v') && env.HOTFIX_STATUS =='success')}}  
        working-directory: ./src
        run: |
          dotnet nuget add source ${{ secrets.nugetGithubHost }} --name github --username ${{ secrets.nugetGithubUsername }} --password ${{ secrets.nugetGithubPassword }} --store-password-in-clear-text
          dotnet nuget add source ${{ secrets.hangfireFeedUrl }} --name hangfirePro --username ${{ secrets.hangfireUsername }} --password ${{ secrets.hangfirePassword }} --store-password-in-clear-text
          dotnet restore
      
      - name: If no release, build service
        working-directory: ./src
        if: ${{!startsWith(github.ref, 'refs/tags/v') || ( startsWith(github.ref, 'refs/tags/v') && env.HOTFIX_STATUS =='success')}}  
        run: 'dotnet publish ${{env.NAME}}.csproj --configuration Release --output Publish -r win-x64 --self-contained true /p:AssemblyVersion=${{ env.VERSION }} /p:FileVersion=${{ env.VERSION }}'
     
      - name: If no release, zip build results
        working-directory: ./src
        if: ${{!startsWith(github.ref, 'refs/tags/v') || ( startsWith(github.ref, 'refs/tags/v') && env.HOTFIX_STATUS =='success')}}  
        run: cd ./Publish; zip -r ${{ env.NAME}}-${{ env.VERSION }}.zip .

      - name: If release, set run number as env variable
        working-directory: ./src
        if:  ${{ startsWith(github.ref, 'refs/tags/v') &&  env.HOTFIX_STATUS =='failure'}}
        run: |
           ENV_VAR_CLEAN=$(echo ${{env.STAGING_RUN_NUMBER}} | tr -d "'")
           echo ENV_VAR_CLEAN=$(echo $ENV_VAR_CLEAN) >> $GITHUB_ENV
           
      - name: If release, zip build results
        working-directory: ./src
        if:  ${{ startsWith(github.ref, 'refs/tags/v') &&  env.HOTFIX_STATUS =='failure'}}
        run: |
           curl -u "${{ secrets.packageRepoUsername }}:${{ secrets.packageRepoPassword }}" ${{ secrets.packageRepoHost }}/staging/${{env.NAME}}/${{env.NAME}}-${{ env.BASE_VERSION }}.${{env.ENV_VAR_CLEAN}}.zip --output ${{env.NAME}}-${{ env.BASE_VERSION }}.${{env.ENV_VAR_CLEAN}}.zip

      - name: Publish zip to nexus release repo
        if: startsWith(github.ref, 'refs/tags/v')
        run:  curl -u "${{ secrets.nexusAptRepoUsername }}:${{ secrets.nexusAptRepoPassword }}" --upload-file ./src/${{env.NAME}}-${{ env.BASE_VERSION }}.${{env.ENV_VAR_CLEAN}}.zip https://nexus.hectorts.de/repository/windows/${{ env.NAME}}-${{ env.BASE_VERSION }}.${{env.ENV_VAR_CLEAN}}.zip

      - name: Publish zip to nexus staging repo
        if: startsWith(github.ref, 'refs/tags/staging-')
        run:  curl -u "${{ secrets.nexusAptRepoUsername }}:${{ secrets.nexusAptRepoPassword }}" --upload-file ./src/Publish/${{ env.NAME}}-${{ env.VERSION }}.zip https://nexus.hectorts.de/repository/windows-stg/${{ env.NAME}}-${{ env.VERSION }}.zip

      - name: Publish zip to nexus prerelease repo
        if: startsWith(github.ref, 'refs/tags/prerelease-')
        run:  curl -u "${{ secrets.nexusAptRepoUsername }}:${{ secrets.nexusAptRepoPassword }}" --upload-file ./src/Publish/${{ env.NAME}}-${{ env.VERSION }}.zip https://nexus.hectorts.de/repository/windows-pre/${{ env.NAME}}-${{ env.VERSION }}.zip

      - name: copy file via ssh password to staging repo
        if: startsWith(github.ref, 'refs/tags/staging-')
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.packageRepoHost }}
          username: ${{ secrets.packageRepoUsername }}
          password: ${{ secrets.packageRepoPassword }}
          port: ${{ secrets.packageRepoPort }}
          source: ./src/Publish/${{ env.NAME}}-${{ env.VERSION }}.zip
          target: staging/${{ env.NAME }}
          strip_components: 3

      - name: copy file via ssh password to release repo as hotfix
        if:  ${{ startsWith(github.ref, 'refs/tags/v')  &&  env.HOTFIX_STATUS =='success'}}
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.packageRepoHost }}
          username: ${{ secrets.packageRepoUsername }}
          password: ${{ secrets.packageRepoPassword }}
          port: ${{ secrets.packageRepoPort }}
          source: ./src/Publish/${{ env.NAME}}-${{ env.VERSION }}.zip
          target: release/${{ env.NAME }}
          strip_components: 3

      - name: copy file via ssh password to release repo
        if:   ${{ startsWith(github.ref, 'refs/tags/v') && env.HOTFIX_STATUS =='failure'}}
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.packageRepoHost }}
          username: ${{ secrets.packageRepoUsername }}
          password: ${{ secrets.packageRepoPassword }}
          port: ${{ secrets.packageRepoPort }}
          source: ./src/${{ env.NAME}}-${{ env.BASE_VERSION }}.${{env.ENV_VAR_CLEAN}}.zip
          target: release/${{ env.NAME }}
          strip_components: 2
          
      - name: copy file via ssh password to prerelease repo
        if: startsWith(github.ref, 'refs/tags/prerelease-')
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.packageRepoHost }}
          username: ${{ secrets.packageRepoUsername }}
          password: ${{ secrets.PackageRepoPassword }}
          port: ${{ secrets.packageRepoPort}}
          source: ./src/Publish/${{ env.NAME}}-${{ env.VERSION }}.zip
          target: prerelease/${{ env.NAME }}
          strip_components: 3
