name: Create v6 publish zip

on:
  workflow_call:
    secrets:
      packageRepoHost: 
        required: true
      packageRepoPassword:
        required: true
      packageRepoUsername:
        required: true
      packageRepoPort:
        required: true
      hangfireFeedUrl:
        required: true  
      hangfireUsername:
        required: true
      hangfirePassword:
        required: true  
      nugetGithubHost:
        required: true
      nugetGithubUsername:
        required: true
      nugetGithubPassword:
        required: true
      dotnetVersion:
        required: true
      stagingRunNumber:
        required: true
env:
  SERVICE: ${{ github.event.repository.name }}
        
jobs:
   build_and_publish_zip:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ secrets.dotnetVersion }}.x
          
      - name: Prepare environment variables for release
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo BASE_VERSION=$(echo ${GITHUB_REF/refs\/tags\/v/}) >> $GITHUB_ENV
          echo VERSION=$(echo ${GITHUB_REF/refs\/tags\/v/}.$GITHUB_RUN_NUMBER) >> $GITHUB_ENV
          echo TAG_NAME=$(echo ${GITHUB_REF/refs\/tags\/}) >> $GITHUB_ENV
          echo NAME=$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}') >> $GITHUB_ENV
          
      - name: Prepare environment variables for staging
        if: startsWith(github.ref, 'refs/tags/staging-')
        run: |
          echo BASE_VERSION=$(echo ${GITHUB_REF/refs\/tags\/staging-/}) >> $GITHUB_ENV
          echo VERSION=$(echo ${GITHUB_REF/refs\/tags\/staging-/}.$GITHUB_RUN_NUMBER) >> $GITHUB_ENV
          echo TAG_NAME=$(echo ${GITHUB_REF/refs\/tags\/}) >> $GITHUB_ENV
          echo NAME=$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}') >> $GITHUB_ENV

      - name: Prepare environment variables for prerelease
        if: startsWith(github.ref, 'refs/tags/prerelease-')
        run: |
          echo BASE_VERSION=$(echo ${GITHUB_REF/refs\/tags\/prerelease-/}) >> $GITHUB_ENV
          echo VERSION=$(echo ${GITHUB_REF/refs\/tags\/prerelease-/}.$GITHUB_RUN_NUMBER) >> $GITHUB_ENV
          echo RUN_NUMBER=$(echo $GITHUB_RUN_NUMBER) >> $GITHUB_ENV
          echo TAG_NAME=$(echo ${GITHUB_REF/refs\/tags\/}) >> $GITHUB_ENV
          echo NAME=$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}') >> $GITHUB_ENV

      - name: if no 'v' tag, add feeds
        if: ${{!startsWith(github.ref, 'refs/tags/v')}}  
        working-directory: ./src
        run: |
          dotnet nuget add source ${{ secrets.nugetGithubHost }} --name github --username ${{ secrets.nugetGithubUsername }} --password ${{ secrets.nugetGithubPassword }} --store-password-in-clear-text
          dotnet nuget add source ${{ secrets.hangfireFeedUrl }} --name hangfirePro --username ${{ secrets.hangfireUsername }} --password ${{ secrets.hangfirePassword }} --store-password-in-clear-text
          dotnet restore
      
      - name: If no 'v' tag, build service
        working-directory: ./src
        if: ${{!startsWith(github.ref, 'refs/tags/v')}}  
        run: 'dotnet publish ${{env.NAME}}.csproj --configuration Release --output Publish -r win-x64 --self-contained true /p:AssemblyVersion=${{ env.VERSION }} /p:FileVersion=${{ env.VERSION }}'
     
      - name: If no 'v' tag, zip build results
        working-directory: ./src
        if: ${{!startsWith(github.ref, 'refs/tags/v')}}  
        run: cd ./Publish; zip -r ${{ env.NAME}}-${{ env.VERSION }}.zip .
           
      - name: If 'v' tag, zip build results
        working-directory: ./src
        if:  ${{ startsWith(github.ref, 'refs/tags/v')}}
        run: |
           curl -u "${{ secrets.packageRepoUsername }}:${{ secrets.packageRepoPassword }}" ${{ secrets.packageRepoHost }}/staging/${{env.NAME}}/${{env.NAME}}-${{ env.BASE_VERSION }}.${{secrets.stagingRunNumber}}.zip --output ${{env.NAME}}-${{ env.BASE_VERSION }}.${{secrets.stagingRunNumber}}.zip

      - name: Publish zip to nexus release repo
        if:   ${{ startsWith(github.ref, 'refs/tags/v')}}
        run:  curl -u "${{ secrets.nexusAptRepoUsername }}:${{ secrets.nexusAptRepoPassword }}" --upload-file ./src/${{env.NAME}}-${{ env.BASE_VERSION }}.${{env.ENV_VAR_CLEAN}}.zip https://nexus.hectorts.de/repository/windows/${{ env.NAME}}-${{ env.BASE_VERSION }}.${{secrets.stagingRunNumber}}.zip

      - name: Publish zip to nexus prerelease repo
        if: startsWith(github.ref, 'refs/tags/prerelease-')
        run:  curl -u "${{ secrets.nexusAptRepoUsername }}:${{ secrets.nexusAptRepoPassword }}" --upload-file ./src/Publish/${{ env.NAME}}-${{ env.VERSION }}.zip https://nexus.hectorts.de/repository/windows-pre/${{ env.NAME}}-${{ env.VERSION }}.zip

      - name: copy file via ssh password to staging repo
        if: startsWith(github.ref, 'refs/tags/staging-')
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.packageRepoHost }}
          username: ${{ secrets.packageRepoUsername }}
          password: ${{ secrets.packageRepoPassword }}
          port: ${{ secrets.packageRepoPort }}
          source: ./src/Publish/${{ env.NAME}}-${{ env.VERSION }}.zip
          target: staging/${{ env.NAME }}
          strip_components: 3

      - name: copy file via ssh password to release repo
        if:   ${{ startsWith(github.ref, 'refs/tags/v')}}
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.packageRepoHost }}
          username: ${{ secrets.packageRepoUsername }}
          password: ${{ secrets.packageRepoPassword }}
          port: ${{ secrets.packageRepoPort }}
          source: ./src/${{ env.NAME}}-${{ env.BASE_VERSION }}.${{secrets.stagingRunNumber}}.zip
          target: release/${{ env.NAME }}
          strip_components: 2
          
      - name: copy file via ssh password to prerelease repo
        if: startsWith(github.ref, 'refs/tags/prerelease-')
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.packageRepoHost }}
          username: ${{ secrets.packageRepoUsername }}
          password: ${{ secrets.PackageRepoPassword }}
          port: ${{ secrets.packageRepoPort}}
          source: ./src/Publish/${{ env.NAME}}-${{ env.VERSION }}.zip
          target: prerelease/${{ env.NAME }}
          strip_components: 3
