name: Create v6 publish deb

on:
  workflow_call:
    secrets:
      hangfireFeedUrl:
        required: true  
      hangfireUsername:
        required: true
      hangfirePassword:
        required: true
      nexusAptRepoUsername:
        required: true
      nexusAptRepoPassword:
        required: true
      nexusAptRepoHost:
        required: true 
      nexusAptRepoPrereleaseHost:
        required: true  
      nugetGithubHost:
        required: true
      nugetGithubUsername:
        required: true
      nugetGithubPassword:
        required: true
      nexusAptRepoStagingHost:
        required: true
 
env:
  SERVICE: ${{ github.event.repository.name }}
        
jobs:
  build_and_publish_deb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.100
      - name: test
        run: 
          echo $NAME
          
      - name: Prepare environment variables
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo BASE_VERSION=$(echo ${GITHUB_REF/refs\/tags\/v/}) >> $GITHUB_ENV
          echo VERSION=$(echo ${GITHUB_REF/refs\/tags\/v/}.$GITHUB_RUN_NUMBER) >> $GITHUB_ENV
          echo TAG_NAME=$(echo ${GITHUB_REF/refs\/tags\/}) >> $GITHUB_ENV
          echo NAME=$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}') >> $GITHUB_ENV

      - name: Prepare environment variables
        if: startsWith(github.ref, 'refs/tags/staging-')
        run: |
          echo BASE_VERSION=$(echo ${GITHUB_REF/refs\/tags\/staging-/}) >> $GITHUB_ENV
          echo VERSION=$(echo ${GITHUB_REF/refs\/tags\/staging-/}.$GITHUB_RUN_NUMBER) >> $GITHUB_ENV
          echo TAG_NAME=$(echo ${GITHUB_REF/refs\/tags\/}) >> $GITHUB_ENV
          echo NAME=$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}') >> $GITHUB_ENV
          
      - name: Prepare environment variables
        if: startsWith(github.ref, 'refs/tags/prerelease-')
        run: |
          echo BASE_VERSION=$(echo ${GITHUB_REF/refs\/tags\/prerelease-/}) >> $GITHUB_ENV
          echo VERSION=$(echo ${GITHUB_REF/refs\/tags\/prerelease-/}.$GITHUB_RUN_NUMBER) >> $GITHUB_ENV
          echo RUN_NUMBER=$(echo $GITHUB_RUN_NUMBER) >> $GITHUB_ENV
          echo TAG_NAME=$(echo ${GITHUB_REF/refs\/tags\/}) >> $GITHUB_ENV
          echo NAME=$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}') >> $GITHUB_ENV

      - name: Check if staging tag exists and get run number
        if: startsWith(github.ref, 'refs/tags/v')
        id: check_staging_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_VERSION=${{ env.BASE_VERSION }}
          STAGING_TAG_NAME="staging-$TAG_VERSION"
          REPO=${{ github.repository }}
          API_RESPONSE=$(curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/$REPO/git/ref/tags/$STAGING_TAG_NAME)
          if [[ $API_RESPONSE == *"ref"* ]]; then
            COMMIT_SHA=$(echo $API_RESPONSE | jq -r '.object.sha')
            RUN_NUMBER=$(curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/$REPO/actions/runs | jq -r '[.workflow_runs[] | select(.head_sha == "'$COMMIT_SHA'" and .conclusion == "success")] | max_by(.run_number) | .run_number')            
            echo "STAGING_TAG_EXISTS=true" >> $GITHUB_ENV
            echo "STAGING_RUN_NUMBER='$RUN_NUMBER'" >> $GITHUB_ENV
          else
            echo "STAGING_TAG_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Check if hotfix
        if: startsWith(github.ref, 'refs/tags/v')
        id: hotfix_check
        run: |
          # Get the latest version with the prefix "v"
          LATEST_VERSION=$(git tag | grep "^v" | sort -V | tail -n 1 | cut -d 'v' -f 2)
      
          # Get the current version (remove the "v" prefix)
          CURRENT_VERSION=$(echo ${GITHUB_REF/refs\/tags\/v/})
      
          # Get the patch versions
          LATEST_PATCH_VERSION=$(echo $LATEST_VERSION | cut -d '.' -f 3)
          CURRENT_PATCH_VERSION=$(echo $CURRENT_VERSION | cut -d '.' -f 3)
      
          # Check if the current patch version is one higher than the latest patch version
          if [[ $((CURRENT_PATCH_VERSION)) == $((LATEST_PATCH_VERSION + 1)) ]]; then
            echo "HOTFIX_STATUS=success" >> $GITHUB_ENV
          else
            echo "HOTFIX_STATUS=failure" >> $GITHUB_ENV
          fi
  
      - name: add feeds
        run: |
          dotnet nuget add source ${{ secrets.nugetGithubHost }} --name github --username ${{ secrets.nugetGithubUsername }} --password ${{ secrets.nugetGithubPassword }} --store-password-in-clear-text
          dotnet nuget add source ${{ secrets.hangfireFeedUrl }} --name hangfirePro --username ${{ secrets.hangfireUsername }} --password ${{ secrets.hangfirePassword }} --store-password-in-clear-text
          dotnet restore

      - name: Publish service
        if: ${{!startsWith(github.ref, 'refs/tags/v')}} || ${{startsWith(github.ref, 'refs/tags/v')}} && ${{env.HOTFIX_STATUS =='success'}}
        run: >
          dotnet publish ./src/${{ env.NAME }}.csproj --configuration Release --output Publish/opt/hector/${{ env.NAME }}
          -r linux-x64 --self-contained true /p:AssemblyVersion=${{ env.VERSION }} /p:FileVersion=${{ env.VERSION }}
          
      - name: Create file paths
        if: ${{!startsWith(github.ref, 'refs/tags/v')}} || ${{startsWith(github.ref, 'refs/tags/v')}} && ${{env.HOTFIX_STATUS =='success'}}
        run: |
          mkdir -p Publish/etc/systemd/system/
          mkdir Publish/DEBIAN
          
      - name: Create systemd unit
        if: ${{!startsWith(github.ref, 'refs/tags/v')}} || ${{startsWith(github.ref, 'refs/tags/v')}} && ${{env.HOTFIX_STATUS =='success'}}
        run: |
          cat << EOF > Publish/etc/systemd/system/${{ env.NAME }}.service
          [Unit]
          Description=Hector ${{ env.NAME }}
          After=network-online.target
          Requires=network-online.target
          
          [Service]
          EnvironmentFile=/etc/serviceEnvironment
          WorkingDirectory=/opt/hector/${{ env.NAME }}
          ExecStart=/opt/hector/${{ env.NAME }}/${{ env.NAME }}
          TimeoutStopSec=1
          Restart=always
          RestartSec=5
          
          [Install]
          WantedBy=multi-user.target
          EOF
          
      - name: Create postinstall script
        if: ${{!startsWith(github.ref, 'refs/tags/v')}} || ${{startsWith(github.ref, 'refs/tags/v')}} && ${{env.HOTFIX_STATUS =='success'}}
        run: |
          cat << EOF > Publish/DEBIAN/postinst
          #!/bin/sh
          systemctl enable ${{env.NAME}}.service --now
          EOF
          chmod 755 Publish/DEBIAN/postinst
          
      - name: Create preremove script
        if: ${{!startsWith(github.ref, 'refs/tags/v')}} || ${{startsWith(github.ref, 'refs/tags/v')}} && ${{env.HOTFIX_STATUS =='success'}}
        run: |
          cat << EOF > Publish/DEBIAN/prerm
          #!/bin/sh
          systemctl disable ${{env.NAME}}.service --now
          EOF
          chmod 755 Publish/DEBIAN/prerm
          
      - name: Set user and group to root
        if: ${{!startsWith(github.ref, 'refs/tags/v')}} || ${{startsWith(github.ref, 'refs/tags/v')}} && ${{env.HOTFIX_STATUS =='success'}}
        run: |
          sudo chown -R root:root Publish
          
      - name: Build deb package
        if: startsWith(github.ref, 'refs/tags/staging-') || startsWith(github.ref, 'refs/tags/prerelease-')
        id: package
        uses: jiro4989/build-deb-action@v2
        with:
          package: ${{ env.NAME }}
          package_root: Publish
          maintainer: "Hectors-Welt GmbH"
          version: ${{ env.VERSION }}
          arch: "amd64"
          desc: Hector ${{ env.NAME }}

      - name: Build deb package
        if:  ${{ startsWith(github.ref, 'refs/tags/v') && env.HOTFIX_STATUS =='success' }}
        id: hotfix
        uses: jiro4989/build-deb-action@v2
        with:
          package: ${{ env.NAME }}
          package_root: Publish
          maintainer: "Hectors-Welt GmbH"
          version: ${{ env.VERSION }}
          arch: "amd64"
          desc: Hector ${{ env.NAME }}

      - name: get package binarys from repo
        if:  ${{ startsWith(github.ref, 'refs/tags/v') && env.HOTFIX_STATUS =='failure'}}
        id: debian_package
        run: |
          firstchar=`echo ${{env.NAME}} | cut -c1-1`
          ENV_VAR_CLEAN=$(echo ${{env.STAGING_RUN_NUMBER}} | tr -d "'")
          echo $ENV_VAR_CLEAN
          curl ${{ secrets.nexusAptRepoStagingHost }}pool/$firstchar/${{env.NAME}}/${{env.NAME}}_${{env.BASE_VERSION}}.$ENV_VAR_CLEAN_amd64.deb --output ${{env.NAME}}_${{env.VERSION}}_amd64.deb 
          
      - name: push deb package to nexus apt repo
        if: ${{ startsWith(github.ref, 'refs/tags/v') &&  env.HOTFIX_STATUS =='failure'}}
        run: |
          curl -u "${{ secrets.nexusAptRepoUsername }}:${{ secrets.nexusAptRepoPassword }}" -H "Content-Type: multipart/form-data" --data-binary "@./${{env.NAME}}_${{env.VERSION}}_amd64.deb" "${{ secrets.nexusAptRepoHost  }}"
      
      - name: push deb package to nexus apt repo
        if: ${{ startsWith(github.ref, 'refs/tags/v') && env.HOTFIX_STATUS =='success'}}
        run: |
          curl -u "${{ secrets.nexusAptRepoUsername }}:${{ secrets.nexusAptRepoPassword }}" -H "Content-Type: multipart/form-data" --data-binary "@${{steps.package.outputs.file_name}}" "${{ secrets.nexusAptRepoHost  }}"

      - name: push deb package to nexus apt repo
        if: startsWith(github.ref, 'refs/tags/staging-')
        run: |
          curl -u "${{ secrets.nexusAptRepoUsername }}:${{ secrets.nexusAptRepoPassword }}" -H "Content-Type: multipart/form-data" --data-binary "@${{steps.package.outputs.file_name}}" "${{ secrets.nexusAptRepoStagingHost  }}"

      - name: push deb package to nexus apt repo
        if: startsWith(github.ref, 'refs/tags/prerelease-')
        run: |
          curl -u "${{ secrets.nexusAptRepoUsername }}:${{ secrets.nexusAptRepoPassword }}" -H "Content-Type: multipart/form-data" --data-binary "@${{steps.package.outputs.file_name}}" "${{ secrets.nexusAptRepoPrereleaseHost  }}"
