name: Create v6 prerelease

on:
  workflow_call:
    secrets:
      dockerRepo:
        required: true
      nexusDockerUsername:
        required: true      
      nexusDockerPassword:
        required: true
      nugetGithubUsername:
        required: true
      nugetGithubPassword:
        required: true
 
env:
  SERVICE: ${{ github.event.repository.name }}
  REGISTRY: ${{ secrets.dockerRepo }}

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:   
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.nexusDockerUsername }}
        password: ${{ secrets.nexusDockerPassword }}

    - name: Prepare environemt variables
      if: startsWith(github.ref, 'refs/tags/prerelease-')
      run: |
        echo BASE_VERSION=$(echo ${GITHUB_REF/refs\/tags\/prerelease-/}) >> $GITHUB_ENV
        echo VERSION=$(echo ${GITHUB_REF/refs\/tags\/prerelease-/}.$GITHUB_RUN_NUMBER) >> $GITHUB_ENV
        echo RUN_NUMBER=$(echo $GITHUB_RUN_NUMBER) >> $GITHUB_ENV
        echo TAG_NAME=$(echo ${GITHUB_REF/refs\/tags\/}) >> $GITHUB_ENV
        echo NAME=$(echo ClubAppService) >> $GITHUB_ENV
        
    - name: Prepare environemt variables
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        echo BASE_VERSION=$(echo ${GITHUB_REF/refs\/tags\/v/}) >> $GITHUB_ENV
        echo VERSION=$(echo ${GITHUB_REF/refs\/tags\/v/}.$GITHUB_RUN_NUMBER) >> $GITHUB_ENV
        echo RUN_NUMBER=$(echo $GITHUB_RUN_NUMBER) >> $GITHUB_ENV
        echo TAG_NAME=$(echo ${GITHUB_REF/refs\/tags\/}) >> $GITHUB_ENV
        echo NAME=$(echo ClubAppService) >> $GITHUB_ENV

    - name: set version in package.json
      run: |
        sed -i '/serviceVersion/c\"serviceVersion": "${{env.VERSION}}",' ./package.json

    - name: create docker file
      run: | 
        cat <<EOF >Dockerfile
        FROM node:12
        ENV NODE_ENV=production
        WORKDIR /usr/src/app
        COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
        RUN npm install --production --silent && mv node_modules ../
        COPY . .
        EXPOSE 80
        RUN chown -R node /usr/src/app
        USER node
        CMD ["node", "dist/index.js"]
        EOF

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v2
      with:
        images: ${{ env.REGISTRY }}/${{ env.SERVICE }}
        flavor: |
          latest=false
        tags: |
          type=ref,event=tag
          
    - name: Get servicename to lowercase
      id: toLowerCase
      run: |
        echo "lowerCaseValue=${{env.NAME}}" >> $GITHUB_OUTPUT  

    - name: Build and push Docker image
      if: startsWith(github.ref, 'refs/tags/v')
      uses: docker/build-push-action@v4
      with:
        context: .
        build-args: |
          SERVICE=${{ env.SERVICE }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}, ${{ secrets.dockerRepo }}/${{steps.toLowerCase.outputs.lowerCaseValue}}:release
        labels: ${{ steps.meta.outputs.labels }}
        file: ./Dockerfile´

    - name: Build and push Docker image
      if: startsWith(github.ref, 'refs/tags/prerelease-')
      uses: docker/build-push-action@v4
      with:
        context: .
        build-args: |
          SERVICE=${{ env.SERVICE }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}, , ${{ secrets.dockerRepo }}/${{steps.toLowerCase.outputs.lowerCaseValue}}:prerelease
        labels: ${{ steps.meta.outputs.labels }}
        file: ./Dockerfile    
