name: Create debian package

on:
  workflow_call:
    secrets:
      nexusAptRepoUsername:
        required: true
      nexusAptRepoPassword:
        required: true
      nexusAptRepoHost:
        required: true
      packageRepoHost:
        required: true
      packageRepoUsername:
        required: true
      packageRepoPassword:
        required: true
      packageRepoPort:
        required: true
        
jobs:
  build_and_publish_zip:
    runs-on: windows-latest
    
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Prepare environemt variables
      run: |
        echo BASE_VERSION=$(echo ${GITHUB_REF/refs\/tags\/prerelease-/}) >> $GITHUB_ENV
        echo VERSION=$(echo ${GITHUB_REF/refs\/tags\/prerelease-/}.$GITHUB_RUN_NUMBER) >> $GITHUB_ENV
        echo RUN_NUMBER=$(echo $GITHUB_RUN_NUMBER) >> $GITHUB_ENV
        echo TAG_NAME=$(echo ${GITHUB_REF/refs\/tags\/}) >> $GITHUB_ENV
        echo NAME=$(echo ClubAppService) >> $GITHUB_ENV
        
    - name: Build service
      run: |
        (Get-Content package.json) -replace 'serviceVersion','${{env.VERSION}}.${{env.RUN_NUMBER}}'
        npm install
        npm run build
        npm run package
        
    - name: Zip build results
      working-directory: ./build
      run: Compress-Archive -Path ./*  -DestinationPath ./${{ github.event.repository.name }}-$(($env:GITHUB_REF -replace "refs/tags/prerelease-")+ "." + ${{github.run_number}}.zip) 
  
    - name: setup SSH connection
      run: Install-Module -Name Posh-SSH -Force

    - name: Setup execution policy
      run:  Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Force -Verbose

    - name: Push zip to repo
      run: Set-SCPItem -ComputerName ${{ secrets.packageRepoHost }} -Credential ${{ secrets.packageRepoUsername }} -Path ./${{ github.event.repository.name }}-$(($env:GITHUB_REF -replace "refs/tags/prerelease-")+"."+(${{github.run_number}}.zip)) -Destination /prerelease/${{ github.event.repository.name }} -Verbose

      
