name: Create debian package for node 18 

on:
  workflow_call:
    secrets:
      nexusAptRepoUsername: 
        required: true
      nexusAptRepoPassword:
        required: true
      nexusAptRepoHost:
        required: true        
      nexusAptRepoPrereleaseHost:
        required: true      
      nexusAptRepoStagingHost:
        required: true   
      nodeVersion:
        required: true
      stagingRunNumber:
        required: true
      isHotfix:
        required: false

env:
  SERVICE: ${{ github.event.repository.name }}

jobs:
  build_debian_package_and_push_to_nexus:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: ${{ secrets.nodeVersion }}
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
      with: 
        fetch-depth: 0
        
    - name: Set isHotfix environment variable
      run: echo "IS_HOTFIX=${{ secrets.isHotfix }}" >> $GITHUB_ENV
      
    - name: Setup Node.js
      if: ${{ env.NODE_VERSION  != null  &&  env.NODE_VERSION != '' }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ secrets.nodeVersion }}.x

    - name: Prepare environment variables for release
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        echo BASE_VERSION=$(echo ${GITHUB_REF/refs\/tags\/v/}) >> $GITHUB_ENV
        echo VERSION=$(echo ${GITHUB_REF/refs\/tags\/v/}.$GITHUB_RUN_NUMBER) >> $GITHUB_ENV
        echo TAG_NAME=$(echo ${GITHUB_REF/refs\/tags\/}) >> $GITHUB_ENV

    - name: Prepare environment variables for prerelease
      if: startsWith(github.ref, 'refs/tags/prerelease-')
      run: |
        echo BASE_VERSION=$(echo ${GITHUB_REF/refs\/tags\/prerelease-/}) >> $GITHUB_ENV
        echo VERSION=$(echo ${GITHUB_REF/refs\/tags\/prerelease-/}.$GITHUB_RUN_NUMBER) >> $GITHUB_ENV
        echo TAG_NAME=$(echo ${GITHUB_REF/refs\/tags\/}) >> $GITHUB_ENV

    - name: Prepare environment variables for staging
      if: startsWith(github.ref, 'refs/tags/staging-')
      run: |
        echo BASE_VERSION=$(echo ${GITHUB_REF/refs\/tags\/staging-/}) >> $GITHUB_ENV
        echo VERSION=$(echo ${GITHUB_REF/refs\/tags\/staging-/}.$GITHUB_RUN_NUMBER) >> $GITHUB_ENV
        echo TAG_NAME=$(echo ${GITHUB_REF/refs\/tags\/}) >> $GITHUB_ENV

    - name: If no 'v' tag, build service 
      if:  ${{ !startsWith(github.ref, 'refs/tags/v') || (startsWith(github.ref, 'refs/tags/v') && env.IS_HOTFIX == 'true') }}
      run: |
        sed -i '/serviceVersion/c\"serviceVersion": "${{env.VERSION}}",' ./package.json
        PUPPETEER_SKIP_DOWNLOAD=true npm i --force
        npm run build
        mkdir -p Publish/opt/hector/${{ env.SERVICE }}/node_modules
        cp -r dist/* Publish/opt/hector/${{ env.SERVICE }}
        mv node_modules/* Publish/opt/hector/${{ env.SERVICE }}/node_modules


    - name: If no 'v' tag, create unit file path
      if:  ${{ !startsWith(github.ref, 'refs/tags/v') || (startsWith(github.ref, 'refs/tags/v') && env.IS_HOTFIX == 'true') }}
      run: |
        mkdir -p Publish/etc/systemd/system/
        mkdir Publish/DEBIAN
    
    - name: If no 'v' tag, Build unit file & startup script
      if:  ${{ !startsWith(github.ref, 'refs/tags/v') || (startsWith(github.ref, 'refs/tags/v') && env.IS_HOTFIX == 'true') }}
      run: |
        startup=Publish/opt/hector/${{ env.SERVICE }}/start.sh
        cat > $startup <<EOF
        #!/bin/bash
        [ -s "/home/services-user/.nvm/nvm.sh" ] && \. "/home/services-user/.nvm/nvm.sh"
        nvm use 18
        node src/main.js
        EOF

        chmod +x $startup
        
        cat << EOF > Publish/etc/systemd/system/${{ env.SERVICE }}.service
        [Unit]
        Description=Hector ${{ env.SERVICE }}
        After=network-online.target
        Requires=network-online.target
        
        [Service]
        EnvironmentFile=/etc/serviceEnvironment
        WorkingDirectory=/opt/hector/${{ env.SERVICE }}
        ExecStart=/opt/hector/${{ env.SERVICE }}/start.sh
        TimeoutStopSec=1
        Restart=always
        RestartSec=5
        
        [Install]
        WantedBy=multi-user.target
        
        EOF

    - name: If no 'v' tag, Create postinstall script
      if:  ${{ !startsWith(github.ref, 'refs/tags/v') || (startsWith(github.ref, 'refs/tags/v') && env.IS_HOTFIX == 'true') }}
      run: |
        cat << EOF > Publish/DEBIAN/postinst
        #!/bin/sh
        systemctl enable ${{env.SERVICE}}.service --now
        EOF
        chmod 755 Publish/DEBIAN/postinst

    - name: If no 'v' tag, create preremove script
      if:  ${{ !startsWith(github.ref, 'refs/tags/v') || (startsWith(github.ref, 'refs/tags/v') && env.IS_HOTFIX == 'true') }}
      run: |
        cat << EOF > Publish/DEBIAN/prerm
        #!/bin/sh
        systemctl disable ${{env.SERVICE}}.service --now
        EOF
        chmod 755 Publish/DEBIAN/prerm

    - name: If no 'v' tag, build-deb-action
      if:  ${{ !startsWith(github.ref, 'refs/tags/v') || (startsWith(github.ref, 'refs/tags/v') && env.IS_HOTFIX == 'true') }}
      id: package
      uses: jiro4989/build-deb-action@v2
      with:
        package: ${{ env.SERVICE }}
        package_root: ./Publish
        maintainer: "Hectors-Welt GmbH"
        version: ${{ env.VERSION }}
        arch: "amd64"
        desc: Hector ${{ env.SERVICE }}

    - name: If 'v' tag, get package binarys from staging repo
      if:  ${{ (startsWith(github.ref, 'refs/tags/v') && env.IS_HOTFIX == 'false') }}
      id: debian_package
      run: |
        FIRST_CHAR=`echo ${{env.SERVICE}} | cut -c1-1`
        echo FIRST_CHAR=$(echo $FIRST_CHAR) >> $GITHUB_ENV
        curl --fail ${{ secrets.nexusAptRepoStagingHost }}pool/${FIRST_CHAR}/${{env.SERVICE}}/${{env.SERVICE}}_${{env.BASE_VERSION}}.${{secrets.stagingRunNumber}}_amd64.deb --output ${{env.SERVICE}}_${{env.BASE_VERSION}}.${{secrets.stagingRunNumber}}_amd64.deb 
  
    - name: If 'v' tag, push deb package to nexus release apt repo 
      if: ${{ (startsWith(github.ref, 'refs/tags/v')  && env.IS_HOTFIX == 'false')}}
      run: |
        ENV_VAR_CLEAN=$(echo ${{secrets.stagingRunNumber}} | tr -d "'")
        echo $ENV_VAR_CLEAN
        curl --fail -u "${{ secrets.nexusAptRepoUsername }}:${{ secrets.nexusAptRepoPassword }}" -H "Content-Type: multipart/form-data" --data-binary "@${{env.SERVICE}}_${{env.BASE_VERSION}}.${ENV_VAR_CLEAN}_amd64.deb" "${{ secrets.nexusAptRepoHost }}"
    
    - name: hotfix, push deb package to nexus apt repo
      if: ${{ (startsWith(github.ref, 'refs/tags/v')  && env.IS_HOTFIX == 'true')}}
      run: |
          curl --fail -u "${{ secrets.nexusAptRepoUsername }}:${{ secrets.nexusAptRepoPassword }}" -H "Content-Type: multipart/form-data" --data-binary "@${{steps.package.outputs.file_name}}" "${{ secrets.nexusAptRepoHost  }}"

    - name: staging, push deb package to nexus apt repo
      if: startsWith(github.ref, 'refs/tags/staging-')
      run: |
        curl --fail -u "${{ secrets.nexusAptRepoUsername }}:${{ secrets.nexusAptRepoPassword }}" -H "Content-Type: multipart/form-data" --data-binary "@${{steps.package.outputs.file_name}}" "${{ secrets.nexusAptRepoStagingHost  }}"

    - name: prerelease, push deb package to nexus apt repo
      if: startsWith(github.ref, 'refs/tags/prerelease-')
      run: |
        curl --fail -u "${{ secrets.nexusAptRepoUsername }}:${{ secrets.nexusAptRepoPassword }}" -H "Content-Type: multipart/form-data" --data-binary "@${{steps.package.outputs.file_name}}" "${{ secrets.nexusAptRepoPrereleaseHost  }}"
