name: Create release of node 20 for clubAppService

on:
  workflow_call:
    secrets:
      nexusAptRepoUsername:
        required: true
      nexusAptRepoPassword:
        required: true
      nexusAptRepoHost:
        required: true
      packageRepoHost:
        required: true
      packageRepoUsername:
        required: true
      packageRepoPassword:
        required: true
      packageRepoPort:
        required: true
        
jobs:
  build_and_publish_deb:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Prepare environemt variables
      run: |
        echo BASE_VERSION=$(echo ${GITHUB_REF/refs\/tags\/v/}) >> $GITHUB_ENV
        echo VERSION=$(echo ${GITHUB_REF/refs\/tags\/v/}.$GITHUB_RUN_NUMBER) >> $GITHUB_ENV
        echo RUN_NUMBER=$(echo $GITHUB_RUN_NUMBER) >> $GITHUB_ENV
        echo TAG_NAME=$(echo ${GITHUB_REF/refs\/tags\/}) >> $GITHUB_ENV
        echo NAME=$(echo ClubAppService) >> $GITHUB_ENV
    - name: Build service
      run: |
        sed -i '/serviceVersion/c\"serviceVersion": "${{env.VERSION}}",' ./package.json
        npm install
        npm run build
        npm run package
        mkdir -p Publish/opt/hector/${{ env.NAME }}
        mv build/* Publish/opt/hector/${{ env.NAME }}
    - name: Create unit file path
      run: | 
        mkdir -p Publish/etc/systemd/system/
        mkdir Publish/DEBIAN

    - name: Build unit file
      run: |
        cat << EOF > Publish/etc/systemd/system/${{ env.NAME }}.service
        [Unit]
        Description=Hector ${{ env.NAME }}
        After=network-online.target
        Requires=network-online.target
        
        [Service]
        EnvironmentFile=/etc/serviceEnvironment
        WorkingDirectory=/opt/hector/${{ env.NAME }}
        ExecStart=/opt/hector/${{ env.NAME }}/${{ env.NAME }}
        TimeoutStopSec=1
        Restart=always
        RestartSec=5
        
        [Install]
        WantedBy=multi-user.target
        
        EOF
  
    - name: Create postinstall script
      run: |
        cat << EOF > Publish/DEBIAN/postinst
        #!/bin/sh
        systemctl enable ${{env.NAME}}.service --now
        EOF
        chmod 755 Publish/DEBIAN/postinst
        
    - name: Create preremove script
      run: |
        cat << EOF > Publish/DEBIAN/prerm
        #!/bin/sh
        systemctl disable ${{env.NAME}}.service --now
        EOF
        chmod 755 Publish/DEBIAN/prerm
        
    - name: build-deb-action
      id: package
      uses: jiro4989/build-deb-action@v2
      with:
        package: ${{ env.NAME }}
        package_root: ./Publish
        maintainer: "Hectors-Welt GmbH"
        version: ${{ env.VERSION }}
        arch: "amd64"
        desc: Hector ${{ env.NAME }}

    - name: push deb package to nexus apt repo
      run: |
        curl -u "${{ secrets.nexusAptRepoUsername }}:${{ secrets.nexusAptRepoPassword }}" -H "Content-Type: multipart/form-data" --data-binary "@${{steps.package.outputs.file_name}}" "${{ secrets.nexusAptRepoHost  }}"
